<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Login user successfully</name>
   <tag></tag>
   <elementGuidId>55466815-11c5-436b-8e47-7f379976c9b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='headlessui-dialog-title-:r2:']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Login user successfully&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>ba852dc4-67e4-470f-b703-ba064196af67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm leading-6 font-medium text-gray-900</value>
      <webElementGuid>89456073-6a1c-4b74-a8c8-aaa60f46977a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headlessui-dialog-title-:r2:</value>
      <webElementGuid>741872b0-4c9d-460d-aeb5-5a43fd6a0609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-headlessui-state</name>
      <type>Main</type>
      <value>open</value>
      <webElementGuid>94648c4b-90ec-4d08-bb1e-b81085b42c7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login user successfully</value>
      <webElementGuid>011d5dee-88f0-49fa-bb77-db10d871d2a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-dialog-title-:r2:&quot;)</value>
      <webElementGuid>5aab6c72-786a-405b-a999-c724b6ff3986</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='headlessui-dialog-title-:r2:']</value>
      <webElementGuid>5622ba24-3384-4a62-9c27-aa906dc758c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-:r0:']/div/div[2]/div/div/div[2]/p</value>
      <webElementGuid>f6a7f4fd-23d0-410a-9d9d-99890f7e737e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bridging the Digital Divide.'])[1]/following::p[1]</value>
      <webElementGuid>65002062-fc0e-404c-9ad1-c5e7e0a6fec2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login user successfully']/parent::*</value>
      <webElementGuid>d4c95ed2-5f41-40ce-8f95-c8941024ba80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>00f13637-0b1f-4f40-9208-19b42ce8481d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'headlessui-dialog-title-:r2:' and (text() = 'Login user successfully' or . = 'Login user successfully')]</value>
      <webElementGuid>2145aff5-9732-4fb4-bd87-26b1fec0b4dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='headlessui-dialog-title-:r5:']</value>
      <webElementGuid>dfeae3b2-86ca-456f-af56-ff80f42ef8b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-:r3:']/div/div[2]/div/div/div[2]/p</value>
      <webElementGuid>113839f1-04ac-482d-aa3f-7f6e081544fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'headlessui-dialog-title-:r5:' and (text() = 'Login user successfully' or . = 'Login user successfully')]</value>
      <webElementGuid>bf7472a6-d38d-4969-a73c-539ee889237f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
