<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih KategoriAcademyProfessional</name>
   <tag></tag>
   <elementGuidId>d828d76f-d111-4c5f-8746-0d4a31add639</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='accountType']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#accountType</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Kategori *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>79ac5a0e-94fa-4de5-9eff-73cc25973053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accountType</value>
      <webElementGuid>820f02bb-982d-4088-9230-2089023ba891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>accountType</value>
      <webElementGuid>a14ef295-d587-4466-b658-7f786cb117b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block flex-1 border-0 bg-transparent py-[14px] px-5 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-base sm:leading-6</value>
      <webElementGuid>89f26ae5-8313-4d7b-b9fe-500e11726c84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih KategoriAcademyProfessional</value>
      <webElementGuid>b4c2c078-b433-4bf6-9ac5-52d4df3186d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accountType&quot;)</value>
      <webElementGuid>18de4e53-b643-4505-a519-f19d1000ced0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='accountType']</value>
      <webElementGuid>471315cf-2880-4b17-bd35-256112b20cbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/form/div/div[2]/div/div[10]/div/div/select</value>
      <webElementGuid>5b77c61b-48f0-4753-bdf3-dae2312674da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/following::select[1]</value>
      <webElementGuid>df28138c-ca45-4508-af52-9dbc992c9027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pendidikan'])[1]/preceding::select[1]</value>
      <webElementGuid>fa937d86-3f2f-4585-b334-adfb5bdb9938</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/select</value>
      <webElementGuid>41fdc989-5eda-4f14-9578-43aecfa9f5bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'accountType' and @name = 'accountType' and (text() = 'Pilih KategoriAcademyProfessional' or . = 'Pilih KategoriAcademyProfessional')]</value>
      <webElementGuid>5be08c9e-d117-4330-8cc4-ca59209b51c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
