<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih JurusanIlmu KomputerTeknik Ele_ad8856</name>
   <tag></tag>
   <elementGuidId>4395a713-2745-4dc2-a4f5-ecf28f7d5e37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='major']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#major</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Pilih Jurusan*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5d23a4e5-44dc-406e-9b8a-28b31f65d7d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>major</value>
      <webElementGuid>a56832c9-4765-4173-bfd8-d57a5e2e4410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>major</value>
      <webElementGuid>9ffddf10-6aa7-406a-97a4-af0cf1d1b872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block w-full px-3 py-[14px] bg-gray-50 border border-gray-300 rounded-lg</value>
      <webElementGuid>ac603521-0b31-4945-b2de-23c575567a9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih JurusanIlmu KomputerTeknik ElektroTeknik TelekomunikasiStatistikaTeknik MesinTeknik KomputerFisikaSistem KomputerInformatikaTeknik IndustriHubungan MasyarakatLainnyaSistem InformasiMatematikaTeknik InformatikaManajemen InformatikaTeknik FisikaRekayasa Perangkat LunakTeknik Kimia</value>
      <webElementGuid>771cbf13-9930-4398-a003-6326788d3681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;major&quot;)</value>
      <webElementGuid>fa7e5bab-8d77-49e0-9f2d-42bcfd97df58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='major']</value>
      <webElementGuid>17740fa6-a866-4fe9-8635-7a157e5adde6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/form/div[2]/div[2]/div/div[2]/div/select</value>
      <webElementGuid>b5e9333c-7651-4be9-9e19-a0f3a8a4182d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[10]/following::select[1]</value>
      <webElementGuid>da489e06-c68c-4fa4-9cfd-7eacbaca6eac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[11]/preceding::select[1]</value>
      <webElementGuid>efca385e-8717-423b-b014-7e51567deaf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>9ac78a4d-6ae1-4b84-93e7-e594bda03e84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'major' and @id = 'major' and (text() = 'Pilih JurusanIlmu KomputerTeknik ElektroTeknik TelekomunikasiStatistikaTeknik MesinTeknik KomputerFisikaSistem KomputerInformatikaTeknik IndustriHubungan MasyarakatLainnyaSistem InformasiMatematikaTeknik InformatikaManajemen InformatikaTeknik FisikaRekayasa Perangkat LunakTeknik Kimia' or . = 'Pilih JurusanIlmu KomputerTeknik ElektroTeknik TelekomunikasiStatistikaTeknik MesinTeknik KomputerFisikaSistem KomputerInformatikaTeknik IndustriHubungan MasyarakatLainnyaSistem InformasiMatematikaTeknik InformatikaManajemen InformatikaTeknik FisikaRekayasa Perangkat LunakTeknik Kimia')]</value>
      <webElementGuid>5110eca0-73ac-42f9-959d-3ac4826499f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
