<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih ProvinsiACEHSUMATERA UTARASUMA_0888d3</name>
   <tag></tag>
   <elementGuidId>6062d597-ed77-45ae-8321-afba87f9f1b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='province']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#province</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Provinsi *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1d42c02b-2d44-41f3-9ebc-d0fea017d1aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>province</value>
      <webElementGuid>f299844b-8439-4da8-8785-f5806e81b67b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>province</value>
      <webElementGuid>a88ea3ab-5523-4997-bca0-ec7f6728fcb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block w-full pl-3 pr-8 py-[14px] bg-gray-50 border border-gray-300 rounded-lg truncate</value>
      <webElementGuid>4782a307-3288-440d-9e1d-0217a64a12a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih ProvinsiACEHSUMATERA UTARASUMATERA BARATRIAUJAMBISUMATERA SELATANBENGKULULAMPUNGKEPULAUAN BANGKA BELITUNGKEPULAUAN RIAUDKI JAKARTAJAWA BARATJAWA TENGAHDI YOGYAKARTAJAWA TIMURBANTENBALINUSA TENGGARA BARATNUSA TENGGARA TIMURKALIMANTAN BARATKALIMANTAN TENGAHKALIMANTAN SELATANKALIMANTAN TIMURKALIMANTAN UTARASULAWESI UTARASULAWESI TENGAHSULAWESI SELATANSULAWESI TENGGARAGORONTALOSULAWESI BARATMALUKUMALUKU UTARAPAPUA BARATPAPUA</value>
      <webElementGuid>d6f845b0-c183-4bb4-954d-c43ba2a506d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;province&quot;)</value>
      <webElementGuid>0e946169-1840-4bf0-88b4-6912a21b3b66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='province']</value>
      <webElementGuid>b7dec801-2e80-42eb-9e31-d5f88121fbe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/form/div/div[2]/div/div[7]/div/select</value>
      <webElementGuid>0345addb-50a2-43b3-b58d-b77927432451</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::select[1]</value>
      <webElementGuid>0015fb07-12fd-4f91-bb2d-69f0a0302d80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/preceding::select[1]</value>
      <webElementGuid>feeaf688-acad-4377-aed6-300eaa38de49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/select</value>
      <webElementGuid>cef841e4-ed3c-4ce9-b7d1-7a942de26ad4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'province' and @name = 'province' and (text() = 'Pilih ProvinsiACEHSUMATERA UTARASUMATERA BARATRIAUJAMBISUMATERA SELATANBENGKULULAMPUNGKEPULAUAN BANGKA BELITUNGKEPULAUAN RIAUDKI JAKARTAJAWA BARATJAWA TENGAHDI YOGYAKARTAJAWA TIMURBANTENBALINUSA TENGGARA BARATNUSA TENGGARA TIMURKALIMANTAN BARATKALIMANTAN TENGAHKALIMANTAN SELATANKALIMANTAN TIMURKALIMANTAN UTARASULAWESI UTARASULAWESI TENGAHSULAWESI SELATANSULAWESI TENGGARAGORONTALOSULAWESI BARATMALUKUMALUKU UTARAPAPUA BARATPAPUA' or . = 'Pilih ProvinsiACEHSUMATERA UTARASUMATERA BARATRIAUJAMBISUMATERA SELATANBENGKULULAMPUNGKEPULAUAN BANGKA BELITUNGKEPULAUAN RIAUDKI JAKARTAJAWA BARATJAWA TENGAHDI YOGYAKARTAJAWA TIMURBANTENBALINUSA TENGGARA BARATNUSA TENGGARA TIMURKALIMANTAN BARATKALIMANTAN TENGAHKALIMANTAN SELATANKALIMANTAN TIMURKALIMANTAN UTARASULAWESI UTARASULAWESI TENGAHSULAWESI SELATANSULAWESI TENGGARAGORONTALOSULAWESI BARATMALUKUMALUKU UTARAPAPUA BARATPAPUA')]</value>
      <webElementGuid>c0d8ea9a-4742-41f0-a00d-efbfd65720e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
