<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih KotaKABUPATEN KEPULAUAN SERIBU_039097</name>
   <tag></tag>
   <elementGuidId>0b84c5f9-48e0-4d38-8aee-56400fd7ea2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='city']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#city</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Kota *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e38e6ddf-a04b-43ac-87c5-daceec787e3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>city</value>
      <webElementGuid>80c8ca2b-24ee-4f38-8781-8580d14f148d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>city</value>
      <webElementGuid>26d862a0-cf64-43cd-8a73-514bc787b11b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block w-full pl-3 pr-8 py-[14px] bg-gray-50 border border-gray-300 rounded-lg truncate</value>
      <webElementGuid>b45e1a70-1433-44d0-8690-2a1fe8d0c36e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih KotaKABUPATEN KEPULAUAN SERIBUKOTA JAKARTA SELATANKOTA JAKARTA TIMURKOTA JAKARTA PUSATKOTA JAKARTA BARATKOTA JAKARTA UTARA</value>
      <webElementGuid>18f4a3cb-6b2e-4692-83d9-e673553174dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;city&quot;)</value>
      <webElementGuid>5fbc3d56-cc94-40ae-ae1e-6b5aa14d2620</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='city']</value>
      <webElementGuid>7ec4dc15-dce5-4055-9d94-3453f0351f93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/form/div/div[2]/div/div[8]/div/select</value>
      <webElementGuid>6ffb64a7-9b38-4980-97ab-cb4c3f14db60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/following::select[1]</value>
      <webElementGuid>db282a61-9b6f-47ee-a007-3cbe24ef5f36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat'])[1]/preceding::select[1]</value>
      <webElementGuid>defba266-99dc-4026-94aa-d6f375be7ed2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/select</value>
      <webElementGuid>cdad0646-bf46-4cef-b401-3300023ded8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'city' and @name = 'city' and (text() = 'Pilih KotaKABUPATEN KEPULAUAN SERIBUKOTA JAKARTA SELATANKOTA JAKARTA TIMURKOTA JAKARTA PUSATKOTA JAKARTA BARATKOTA JAKARTA UTARA' or . = 'Pilih KotaKABUPATEN KEPULAUAN SERIBUKOTA JAKARTA SELATANKOTA JAKARTA TIMURKOTA JAKARTA PUSATKOTA JAKARTA BARATKOTA JAKARTA UTARA')]</value>
      <webElementGuid>1fc9471f-f9b0-4277-93c6-2bba1b038c4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
